export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const ADD_USER = 'ADD_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';

export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const UPDATE_POST = 'UPDATE_POST';
